import type { NextPage } from "next";
import Head from "next/head";
import { trpc } from "../utils/trpc";
import CheapFlightsForm from "../components/CheapFlightsForm";

const Home: NextPage = () => {
  const {
    data,
    error,
    isLoading,
    mutate: findCheapestFlight,
  } = trpc.flights.cheapestFlight.useMutation()

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="container mx-auto flex min-h-screen flex-col items-center justify-center p-4">
        {isLoading && (
          <p>Loading...</p>
        )}

        {!data && (
          <CheapFlightsForm
            error={error}
            onSubmit={findCheapestFlight}
          />
        )}

        {data && (
          <p>
            {data.price}
          </p>
        )}
      </main>
    </>
  );
};

export default Home;
